//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalBD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql5113.site4now.net;Initial Catalog=db_ac0671_final;Persist Security" +
            " Info=True;User ID=db_ac0671_final_admin;Encrypt=False;TrustServerCertificate=Tr" +
            "ue")]
        public string db_ac0671_finalConnectionString {
            get {
                return ((string)(this["db_ac0671_finalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql5113.site4now.net;Persist Security Info=True;User ID=db_ac0671_fin" +
            "al_admin;Encrypt=False")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql5113.site4now.net;Initial Catalog=db_ac0671_final;Persist Security" +
            " Info=True;User ID=db_ac0671_final_admin;Encrypt=True;TrustServerCertificate=Tru" +
            "e")]
        public string db_ac0671_finalConnectionString1 {
            get {
                return ((string)(this["db_ac0671_finalConnectionString1"]));
            }
        }
    }
}
