#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalBD.Tecnico.BD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_ac0671_final")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertContrato(Contrato instance);
    partial void UpdateContrato(Contrato instance);
    partial void DeleteContrato(Contrato instance);
    partial void InsertEstado_contrato(Estado_contrato instance);
    partial void UpdateEstado_contrato(Estado_contrato instance);
    partial void DeleteEstado_contrato(Estado_contrato instance);
    partial void InsertVisita_tecnica(Visita_tecnica instance);
    partial void UpdateVisita_tecnica(Visita_tecnica instance);
    partial void DeleteVisita_tecnica(Visita_tecnica instance);
    partial void InsertPeloton(Peloton instance);
    partial void UpdatePeloton(Peloton instance);
    partial void DeletePeloton(Peloton instance);
    partial void InsertTecnico(Tecnico instance);
    partial void UpdateTecnico(Tecnico instance);
    partial void DeleteTecnico(Tecnico instance);
    partial void InsertBitacora(Bitacora instance);
    partial void UpdateBitacora(Bitacora instance);
    partial void DeleteBitacora(Bitacora instance);
    partial void InsertFalla(Falla instance);
    partial void UpdateFalla(Falla instance);
    partial void DeleteFalla(Falla instance);
    partial void Insertrepuesto_falla(repuesto_falla instance);
    partial void Updaterepuesto_falla(repuesto_falla instance);
    partial void Deleterepuesto_falla(repuesto_falla instance);
    partial void InsertRepuesto(Repuesto instance);
    partial void UpdateRepuesto(Repuesto instance);
    partial void DeleteRepuesto(Repuesto instance);
    partial void InsertTipo_falla(Tipo_falla instance);
    partial void UpdateTipo_falla(Tipo_falla instance);
    partial void DeleteTipo_falla(Tipo_falla instance);
    partial void InsertEstado_falla(Estado_falla instance);
    partial void UpdateEstado_falla(Estado_falla instance);
    partial void DeleteEstado_falla(Estado_falla instance);
    #endregion
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Contrato> Contrato
		{
			get
			{
				return this.GetTable<Contrato>();
			}
		}
		
		public System.Data.Linq.Table<Estado_contrato> Estado_contrato
		{
			get
			{
				return this.GetTable<Estado_contrato>();
			}
		}
		
		public System.Data.Linq.Table<Visita_tecnica> Visita_tecnica
		{
			get
			{
				return this.GetTable<Visita_tecnica>();
			}
		}
		
		public System.Data.Linq.Table<Peloton> Peloton
		{
			get
			{
				return this.GetTable<Peloton>();
			}
		}
		
		public System.Data.Linq.Table<Tecnico> Tecnico
		{
			get
			{
				return this.GetTable<Tecnico>();
			}
		}
		
		public System.Data.Linq.Table<Bitacora> Bitacora
		{
			get
			{
				return this.GetTable<Bitacora>();
			}
		}
		
		public System.Data.Linq.Table<Falla> Falla
		{
			get
			{
				return this.GetTable<Falla>();
			}
		}
		
		public System.Data.Linq.Table<repuesto_falla> repuesto_falla
		{
			get
			{
				return this.GetTable<repuesto_falla>();
			}
		}
		
		public System.Data.Linq.Table<Repuesto> Repuesto
		{
			get
			{
				return this.GetTable<Repuesto>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_falla> Tipo_falla
		{
			get
			{
				return this.GetTable<Tipo_falla>();
			}
		}
		
		public System.Data.Linq.Table<Estado_falla> Estado_falla
		{
			get
			{
				return this.GetTable<Estado_falla>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_cliente;
		
		private string _dpi;
		
		private string _nombre;
		
		private string _telefono_primario;
		
		private string _telefono_secundario;
		
		private string _email;
		
		private EntitySet<Contrato> _Contrato;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    partial void OndpiChanging(string value);
    partial void OndpiChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ontelefono_primarioChanging(string value);
    partial void Ontelefono_primarioChanged();
    partial void Ontelefono_secundarioChanging(string value);
    partial void Ontelefono_secundarioChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Cliente()
		{
			this._Contrato = new EntitySet<Contrato>(new Action<Contrato>(this.attach_Contrato), new Action<Contrato>(this.detach_Contrato));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string dpi
		{
			get
			{
				return this._dpi;
			}
			set
			{
				if ((this._dpi != value))
				{
					this.OndpiChanging(value);
					this.SendPropertyChanging();
					this._dpi = value;
					this.SendPropertyChanged("dpi");
					this.OndpiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_primario", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string telefono_primario
		{
			get
			{
				return this._telefono_primario;
			}
			set
			{
				if ((this._telefono_primario != value))
				{
					this.Ontelefono_primarioChanging(value);
					this.SendPropertyChanging();
					this._telefono_primario = value;
					this.SendPropertyChanged("telefono_primario");
					this.Ontelefono_primarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_secundario", DbType="Char(10)")]
		public string telefono_secundario
		{
			get
			{
				return this._telefono_secundario;
			}
			set
			{
				if ((this._telefono_secundario != value))
				{
					this.Ontelefono_secundarioChanging(value);
					this.SendPropertyChanging();
					this._telefono_secundario = value;
					this.SendPropertyChanged("telefono_secundario");
					this.Ontelefono_secundarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contrato", Storage="_Contrato", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<Contrato> Contrato
		{
			get
			{
				return this._Contrato;
			}
			set
			{
				this._Contrato.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contrato(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Contrato(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contrato")]
	public partial class Contrato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_contrato;
		
		private string _id_info_cobro;
		
		private string _id_municipio;
		
		private string _id_cliente;
		
		private string _fecha_inicio;
		
		private System.DateTime _fecha_fin;
		
		private string _direccion_instalacion;
		
		private decimal _saldo_total;
		
		private string _id_estado_contrato;
		
		private string _id_usuario;
		
		private EntitySet<Visita_tecnica> _Visita_tecnica;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Estado_contrato> _Estado_contrato;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contratoChanging(string value);
    partial void Onid_contratoChanged();
    partial void Onid_info_cobroChanging(string value);
    partial void Onid_info_cobroChanged();
    partial void Onid_municipioChanging(string value);
    partial void Onid_municipioChanged();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    partial void Onfecha_inicioChanging(string value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void Ondireccion_instalacionChanging(string value);
    partial void Ondireccion_instalacionChanged();
    partial void Onsaldo_totalChanging(decimal value);
    partial void Onsaldo_totalChanged();
    partial void Onid_estado_contratoChanging(string value);
    partial void Onid_estado_contratoChanged();
    partial void Onid_usuarioChanging(string value);
    partial void Onid_usuarioChanged();
    #endregion
		
		public Contrato()
		{
			this._Visita_tecnica = new EntitySet<Visita_tecnica>(new Action<Visita_tecnica>(this.attach_Visita_tecnica), new Action<Visita_tecnica>(this.detach_Visita_tecnica));
			this._Cliente = default(EntityRef<Cliente>);
			this._Estado_contrato = default(EntityRef<Estado_contrato>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contrato", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_contrato
		{
			get
			{
				return this._id_contrato;
			}
			set
			{
				if ((this._id_contrato != value))
				{
					this.Onid_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_contrato = value;
					this.SendPropertyChanged("id_contrato");
					this.Onid_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_info_cobro", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_info_cobro
		{
			get
			{
				return this._id_info_cobro;
			}
			set
			{
				if ((this._id_info_cobro != value))
				{
					this.Onid_info_cobroChanging(value);
					this.SendPropertyChanging();
					this._id_info_cobro = value;
					this.SendPropertyChanged("id_info_cobro");
					this.Onid_info_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_instalacion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_instalacion
		{
			get
			{
				return this._direccion_instalacion;
			}
			set
			{
				if ((this._direccion_instalacion != value))
				{
					this.Ondireccion_instalacionChanging(value);
					this.SendPropertyChanging();
					this._direccion_instalacion = value;
					this.SendPropertyChanged("direccion_instalacion");
					this.Ondireccion_instalacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_total", DbType="Decimal(8,2) NOT NULL")]
		public decimal saldo_total
		{
			get
			{
				return this._saldo_total;
			}
			set
			{
				if ((this._saldo_total != value))
				{
					this.Onsaldo_totalChanging(value);
					this.SendPropertyChanging();
					this._saldo_total = value;
					this.SendPropertyChanged("saldo_total");
					this.Onsaldo_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_contrato", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_estado_contrato
		{
			get
			{
				return this._id_estado_contrato;
			}
			set
			{
				if ((this._id_estado_contrato != value))
				{
					if (this._Estado_contrato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estado_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_estado_contrato = value;
					this.SendPropertyChanged("id_estado_contrato");
					this.Onid_estado_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contrato_Visita_tecnica", Storage="_Visita_tecnica", ThisKey="id_contrato", OtherKey="id_contrato")]
		public EntitySet<Visita_tecnica> Visita_tecnica
		{
			get
			{
				return this._Visita_tecnica;
			}
			set
			{
				this._Visita_tecnica.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contrato", Storage="_Cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Contrato.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Contrato.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_contrato_Contrato", Storage="_Estado_contrato", ThisKey="id_estado_contrato", OtherKey="id_estado_contrato", IsForeignKey=true)]
		public Estado_contrato Estado_contrato
		{
			get
			{
				return this._Estado_contrato.Entity;
			}
			set
			{
				Estado_contrato previousValue = this._Estado_contrato.Entity;
				if (((previousValue != value) 
							|| (this._Estado_contrato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado_contrato.Entity = null;
						previousValue.Contrato.Remove(this);
					}
					this._Estado_contrato.Entity = value;
					if ((value != null))
					{
						value.Contrato.Add(this);
						this._id_estado_contrato = value.id_estado_contrato;
					}
					else
					{
						this._id_estado_contrato = default(string);
					}
					this.SendPropertyChanged("Estado_contrato");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita_tecnica(Visita_tecnica entity)
		{
			this.SendPropertyChanging();
			entity.Contrato = this;
		}
		
		private void detach_Visita_tecnica(Visita_tecnica entity)
		{
			this.SendPropertyChanging();
			entity.Contrato = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_contrato")]
	public partial class Estado_contrato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_estado_contrato;
		
		private string _nombre_estado_contrato;
		
		private EntitySet<Contrato> _Contrato;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estado_contratoChanging(string value);
    partial void Onid_estado_contratoChanged();
    partial void Onnombre_estado_contratoChanging(string value);
    partial void Onnombre_estado_contratoChanged();
    #endregion
		
		public Estado_contrato()
		{
			this._Contrato = new EntitySet<Contrato>(new Action<Contrato>(this.attach_Contrato), new Action<Contrato>(this.detach_Contrato));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_contrato", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_estado_contrato
		{
			get
			{
				return this._id_estado_contrato;
			}
			set
			{
				if ((this._id_estado_contrato != value))
				{
					this.Onid_estado_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_estado_contrato = value;
					this.SendPropertyChanged("id_estado_contrato");
					this.Onid_estado_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_estado_contrato", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string nombre_estado_contrato
		{
			get
			{
				return this._nombre_estado_contrato;
			}
			set
			{
				if ((this._nombre_estado_contrato != value))
				{
					this.Onnombre_estado_contratoChanging(value);
					this.SendPropertyChanging();
					this._nombre_estado_contrato = value;
					this.SendPropertyChanged("nombre_estado_contrato");
					this.Onnombre_estado_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_contrato_Contrato", Storage="_Contrato", ThisKey="id_estado_contrato", OtherKey="id_estado_contrato")]
		public EntitySet<Contrato> Contrato
		{
			get
			{
				return this._Contrato;
			}
			set
			{
				this._Contrato.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contrato(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Estado_contrato = this;
		}
		
		private void detach_Contrato(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Estado_contrato = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visita_tecnica")]
	public partial class Visita_tecnica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_visita_tecnica;
		
		private string _id_contrato;
		
		private string _id_peloton;
		
		private System.DateTime _fecha_solicitud;
		
		private System.Nullable<System.DateTime> _fecha_ejecucion;
		
		private EntitySet<Bitacora> _Bitacora;
		
		private EntitySet<Falla> _Falla;
		
		private EntityRef<Contrato> _Contrato;
		
		private EntityRef<Peloton> _Peloton;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_visita_tecnicaChanging(string value);
    partial void Onid_visita_tecnicaChanged();
    partial void Onid_contratoChanging(string value);
    partial void Onid_contratoChanged();
    partial void Onid_pelotonChanging(string value);
    partial void Onid_pelotonChanged();
    partial void Onfecha_solicitudChanging(System.DateTime value);
    partial void Onfecha_solicitudChanged();
    partial void Onfecha_ejecucionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ejecucionChanged();
    #endregion
		
		public Visita_tecnica()
		{
			this._Bitacora = new EntitySet<Bitacora>(new Action<Bitacora>(this.attach_Bitacora), new Action<Bitacora>(this.detach_Bitacora));
			this._Falla = new EntitySet<Falla>(new Action<Falla>(this.attach_Falla), new Action<Falla>(this.detach_Falla));
			this._Contrato = default(EntityRef<Contrato>);
			this._Peloton = default(EntityRef<Peloton>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_visita_tecnica", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_visita_tecnica
		{
			get
			{
				return this._id_visita_tecnica;
			}
			set
			{
				if ((this._id_visita_tecnica != value))
				{
					this.Onid_visita_tecnicaChanging(value);
					this.SendPropertyChanging();
					this._id_visita_tecnica = value;
					this.SendPropertyChanged("id_visita_tecnica");
					this.Onid_visita_tecnicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contrato", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_contrato
		{
			get
			{
				return this._id_contrato;
			}
			set
			{
				if ((this._id_contrato != value))
				{
					if (this._Contrato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_contrato = value;
					this.SendPropertyChanged("id_contrato");
					this.Onid_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peloton", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_peloton
		{
			get
			{
				return this._id_peloton;
			}
			set
			{
				if ((this._id_peloton != value))
				{
					if (this._Peloton.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pelotonChanging(value);
					this.SendPropertyChanging();
					this._id_peloton = value;
					this.SendPropertyChanged("id_peloton");
					this.Onid_pelotonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_solicitud", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_solicitud
		{
			get
			{
				return this._fecha_solicitud;
			}
			set
			{
				if ((this._fecha_solicitud != value))
				{
					this.Onfecha_solicitudChanging(value);
					this.SendPropertyChanging();
					this._fecha_solicitud = value;
					this.SendPropertyChanged("fecha_solicitud");
					this.Onfecha_solicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ejecucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_ejecucion
		{
			get
			{
				return this._fecha_ejecucion;
			}
			set
			{
				if ((this._fecha_ejecucion != value))
				{
					this.Onfecha_ejecucionChanging(value);
					this.SendPropertyChanging();
					this._fecha_ejecucion = value;
					this.SendPropertyChanged("fecha_ejecucion");
					this.Onfecha_ejecucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visita_tecnica_Bitacora", Storage="_Bitacora", ThisKey="id_visita_tecnica", OtherKey="id_visita_tecnica")]
		public EntitySet<Bitacora> Bitacora
		{
			get
			{
				return this._Bitacora;
			}
			set
			{
				this._Bitacora.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visita_tecnica_Falla", Storage="_Falla", ThisKey="id_visita_tecnica", OtherKey="id_visita_tecnica")]
		public EntitySet<Falla> Falla
		{
			get
			{
				return this._Falla;
			}
			set
			{
				this._Falla.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contrato_Visita_tecnica", Storage="_Contrato", ThisKey="id_contrato", OtherKey="id_contrato", IsForeignKey=true)]
		public Contrato Contrato
		{
			get
			{
				return this._Contrato.Entity;
			}
			set
			{
				Contrato previousValue = this._Contrato.Entity;
				if (((previousValue != value) 
							|| (this._Contrato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contrato.Entity = null;
						previousValue.Visita_tecnica.Remove(this);
					}
					this._Contrato.Entity = value;
					if ((value != null))
					{
						value.Visita_tecnica.Add(this);
						this._id_contrato = value.id_contrato;
					}
					else
					{
						this._id_contrato = default(string);
					}
					this.SendPropertyChanged("Contrato");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Peloton_Visita_tecnica", Storage="_Peloton", ThisKey="id_peloton", OtherKey="id_peloton", IsForeignKey=true)]
		public Peloton Peloton
		{
			get
			{
				return this._Peloton.Entity;
			}
			set
			{
				Peloton previousValue = this._Peloton.Entity;
				if (((previousValue != value) 
							|| (this._Peloton.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Peloton.Entity = null;
						previousValue.Visita_tecnica.Remove(this);
					}
					this._Peloton.Entity = value;
					if ((value != null))
					{
						value.Visita_tecnica.Add(this);
						this._id_peloton = value.id_peloton;
					}
					else
					{
						this._id_peloton = default(string);
					}
					this.SendPropertyChanged("Peloton");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Visita_tecnica = this;
		}
		
		private void detach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Visita_tecnica = null;
		}
		
		private void attach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Visita_tecnica = this;
		}
		
		private void detach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Visita_tecnica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Peloton")]
	public partial class Peloton : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_peloton;
		
		private string _id_tecnico;
		
		private EntitySet<Visita_tecnica> _Visita_tecnica;
		
		private EntitySet<Bitacora> _Bitacora;
		
		private EntityRef<Tecnico> _Tecnico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pelotonChanging(string value);
    partial void Onid_pelotonChanged();
    partial void Onid_tecnicoChanging(string value);
    partial void Onid_tecnicoChanged();
    #endregion
		
		public Peloton()
		{
			this._Visita_tecnica = new EntitySet<Visita_tecnica>(new Action<Visita_tecnica>(this.attach_Visita_tecnica), new Action<Visita_tecnica>(this.detach_Visita_tecnica));
			this._Bitacora = new EntitySet<Bitacora>(new Action<Bitacora>(this.attach_Bitacora), new Action<Bitacora>(this.detach_Bitacora));
			this._Tecnico = default(EntityRef<Tecnico>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peloton", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_peloton
		{
			get
			{
				return this._id_peloton;
			}
			set
			{
				if ((this._id_peloton != value))
				{
					this.Onid_pelotonChanging(value);
					this.SendPropertyChanging();
					this._id_peloton = value;
					this.SendPropertyChanged("id_peloton");
					this.Onid_pelotonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tecnico", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_tecnico
		{
			get
			{
				return this._id_tecnico;
			}
			set
			{
				if ((this._id_tecnico != value))
				{
					if (this._Tecnico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._id_tecnico = value;
					this.SendPropertyChanged("id_tecnico");
					this.Onid_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Peloton_Visita_tecnica", Storage="_Visita_tecnica", ThisKey="id_peloton", OtherKey="id_peloton")]
		public EntitySet<Visita_tecnica> Visita_tecnica
		{
			get
			{
				return this._Visita_tecnica;
			}
			set
			{
				this._Visita_tecnica.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Peloton_Bitacora", Storage="_Bitacora", ThisKey="id_peloton", OtherKey="id_peloton")]
		public EntitySet<Bitacora> Bitacora
		{
			get
			{
				return this._Bitacora;
			}
			set
			{
				this._Bitacora.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tecnico_Peloton", Storage="_Tecnico", ThisKey="id_tecnico", OtherKey="id_tecnico", IsForeignKey=true)]
		public Tecnico Tecnico
		{
			get
			{
				return this._Tecnico.Entity;
			}
			set
			{
				Tecnico previousValue = this._Tecnico.Entity;
				if (((previousValue != value) 
							|| (this._Tecnico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tecnico.Entity = null;
						previousValue.Peloton.Remove(this);
					}
					this._Tecnico.Entity = value;
					if ((value != null))
					{
						value.Peloton.Add(this);
						this._id_tecnico = value.id_tecnico;
					}
					else
					{
						this._id_tecnico = default(string);
					}
					this.SendPropertyChanged("Tecnico");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita_tecnica(Visita_tecnica entity)
		{
			this.SendPropertyChanging();
			entity.Peloton = this;
		}
		
		private void detach_Visita_tecnica(Visita_tecnica entity)
		{
			this.SendPropertyChanging();
			entity.Peloton = null;
		}
		
		private void attach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Peloton = this;
		}
		
		private void detach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Peloton = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tecnico")]
	public partial class Tecnico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_tecnico;
		
		private string _nombre_tecnico;
		
		private string _direccion_tecnico;
		
		private string _nit_tecnico;
		
		private string _dpi_tecnico;
		
		private System.DateTime _fecha_nacimiento_tecnico;
		
		private System.DateTime _fecha_contrato_tecnico;
		
		private System.DateTime _fecha_despido_tecnico;
		
		private string _id_usuario;
		
		private EntitySet<Peloton> _Peloton;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tecnicoChanging(string value);
    partial void Onid_tecnicoChanged();
    partial void Onnombre_tecnicoChanging(string value);
    partial void Onnombre_tecnicoChanged();
    partial void Ondireccion_tecnicoChanging(string value);
    partial void Ondireccion_tecnicoChanged();
    partial void Onnit_tecnicoChanging(string value);
    partial void Onnit_tecnicoChanged();
    partial void Ondpi_tecnicoChanging(string value);
    partial void Ondpi_tecnicoChanged();
    partial void Onfecha_nacimiento_tecnicoChanging(System.DateTime value);
    partial void Onfecha_nacimiento_tecnicoChanged();
    partial void Onfecha_contrato_tecnicoChanging(System.DateTime value);
    partial void Onfecha_contrato_tecnicoChanged();
    partial void Onfecha_despido_tecnicoChanging(System.DateTime value);
    partial void Onfecha_despido_tecnicoChanged();
    partial void Onid_usuarioChanging(string value);
    partial void Onid_usuarioChanged();
    #endregion
		
		public Tecnico()
		{
			this._Peloton = new EntitySet<Peloton>(new Action<Peloton>(this.attach_Peloton), new Action<Peloton>(this.detach_Peloton));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tecnico", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_tecnico
		{
			get
			{
				return this._id_tecnico;
			}
			set
			{
				if ((this._id_tecnico != value))
				{
					this.Onid_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._id_tecnico = value;
					this.SendPropertyChanged("id_tecnico");
					this.Onid_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tecnico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_tecnico
		{
			get
			{
				return this._nombre_tecnico;
			}
			set
			{
				if ((this._nombre_tecnico != value))
				{
					this.Onnombre_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._nombre_tecnico = value;
					this.SendPropertyChanged("nombre_tecnico");
					this.Onnombre_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_tecnico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_tecnico
		{
			get
			{
				return this._direccion_tecnico;
			}
			set
			{
				if ((this._direccion_tecnico != value))
				{
					this.Ondireccion_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._direccion_tecnico = value;
					this.SendPropertyChanged("direccion_tecnico");
					this.Ondireccion_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_tecnico", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string nit_tecnico
		{
			get
			{
				return this._nit_tecnico;
			}
			set
			{
				if ((this._nit_tecnico != value))
				{
					this.Onnit_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._nit_tecnico = value;
					this.SendPropertyChanged("nit_tecnico");
					this.Onnit_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi_tecnico", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string dpi_tecnico
		{
			get
			{
				return this._dpi_tecnico;
			}
			set
			{
				if ((this._dpi_tecnico != value))
				{
					this.Ondpi_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._dpi_tecnico = value;
					this.SendPropertyChanged("dpi_tecnico");
					this.Ondpi_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento_tecnico", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_nacimiento_tecnico
		{
			get
			{
				return this._fecha_nacimiento_tecnico;
			}
			set
			{
				if ((this._fecha_nacimiento_tecnico != value))
				{
					this.Onfecha_nacimiento_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento_tecnico = value;
					this.SendPropertyChanged("fecha_nacimiento_tecnico");
					this.Onfecha_nacimiento_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_contrato_tecnico", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_contrato_tecnico
		{
			get
			{
				return this._fecha_contrato_tecnico;
			}
			set
			{
				if ((this._fecha_contrato_tecnico != value))
				{
					this.Onfecha_contrato_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._fecha_contrato_tecnico = value;
					this.SendPropertyChanged("fecha_contrato_tecnico");
					this.Onfecha_contrato_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_despido_tecnico", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_despido_tecnico
		{
			get
			{
				return this._fecha_despido_tecnico;
			}
			set
			{
				if ((this._fecha_despido_tecnico != value))
				{
					this.Onfecha_despido_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._fecha_despido_tecnico = value;
					this.SendPropertyChanged("fecha_despido_tecnico");
					this.Onfecha_despido_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tecnico_Peloton", Storage="_Peloton", ThisKey="id_tecnico", OtherKey="id_tecnico")]
		public EntitySet<Peloton> Peloton
		{
			get
			{
				return this._Peloton;
			}
			set
			{
				this._Peloton.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Peloton(Peloton entity)
		{
			this.SendPropertyChanging();
			entity.Tecnico = this;
		}
		
		private void detach_Peloton(Peloton entity)
		{
			this.SendPropertyChanging();
			entity.Tecnico = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bitacora")]
	public partial class Bitacora : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_bitacora;
		
		private string _id_peloton;
		
		private string _id_falla;
		
		private string _id_visita_tecnica;
		
		private EntityRef<Peloton> _Peloton;
		
		private EntityRef<Visita_tecnica> _Visita_tecnica;
		
		private EntityRef<Falla> _Falla;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_bitacoraChanging(string value);
    partial void Onid_bitacoraChanged();
    partial void Onid_pelotonChanging(string value);
    partial void Onid_pelotonChanged();
    partial void Onid_fallaChanging(string value);
    partial void Onid_fallaChanged();
    partial void Onid_visita_tecnicaChanging(string value);
    partial void Onid_visita_tecnicaChanged();
    #endregion
		
		public Bitacora()
		{
			this._Peloton = default(EntityRef<Peloton>);
			this._Visita_tecnica = default(EntityRef<Visita_tecnica>);
			this._Falla = default(EntityRef<Falla>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bitacora", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_bitacora
		{
			get
			{
				return this._id_bitacora;
			}
			set
			{
				if ((this._id_bitacora != value))
				{
					this.Onid_bitacoraChanging(value);
					this.SendPropertyChanging();
					this._id_bitacora = value;
					this.SendPropertyChanged("id_bitacora");
					this.Onid_bitacoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peloton", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_peloton
		{
			get
			{
				return this._id_peloton;
			}
			set
			{
				if ((this._id_peloton != value))
				{
					if (this._Peloton.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pelotonChanging(value);
					this.SendPropertyChanging();
					this._id_peloton = value;
					this.SendPropertyChanged("id_peloton");
					this.Onid_pelotonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_falla
		{
			get
			{
				return this._id_falla;
			}
			set
			{
				if ((this._id_falla != value))
				{
					if (this._Falla.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_falla = value;
					this.SendPropertyChanged("id_falla");
					this.Onid_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_visita_tecnica", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_visita_tecnica
		{
			get
			{
				return this._id_visita_tecnica;
			}
			set
			{
				if ((this._id_visita_tecnica != value))
				{
					if (this._Visita_tecnica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_visita_tecnicaChanging(value);
					this.SendPropertyChanging();
					this._id_visita_tecnica = value;
					this.SendPropertyChanged("id_visita_tecnica");
					this.Onid_visita_tecnicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Peloton_Bitacora", Storage="_Peloton", ThisKey="id_peloton", OtherKey="id_peloton", IsForeignKey=true)]
		public Peloton Peloton
		{
			get
			{
				return this._Peloton.Entity;
			}
			set
			{
				Peloton previousValue = this._Peloton.Entity;
				if (((previousValue != value) 
							|| (this._Peloton.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Peloton.Entity = null;
						previousValue.Bitacora.Remove(this);
					}
					this._Peloton.Entity = value;
					if ((value != null))
					{
						value.Bitacora.Add(this);
						this._id_peloton = value.id_peloton;
					}
					else
					{
						this._id_peloton = default(string);
					}
					this.SendPropertyChanged("Peloton");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visita_tecnica_Bitacora", Storage="_Visita_tecnica", ThisKey="id_visita_tecnica", OtherKey="id_visita_tecnica", IsForeignKey=true)]
		public Visita_tecnica Visita_tecnica
		{
			get
			{
				return this._Visita_tecnica.Entity;
			}
			set
			{
				Visita_tecnica previousValue = this._Visita_tecnica.Entity;
				if (((previousValue != value) 
							|| (this._Visita_tecnica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Visita_tecnica.Entity = null;
						previousValue.Bitacora.Remove(this);
					}
					this._Visita_tecnica.Entity = value;
					if ((value != null))
					{
						value.Bitacora.Add(this);
						this._id_visita_tecnica = value.id_visita_tecnica;
					}
					else
					{
						this._id_visita_tecnica = default(string);
					}
					this.SendPropertyChanged("Visita_tecnica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Falla_Bitacora", Storage="_Falla", ThisKey="id_falla", OtherKey="id_falla", IsForeignKey=true)]
		public Falla Falla
		{
			get
			{
				return this._Falla.Entity;
			}
			set
			{
				Falla previousValue = this._Falla.Entity;
				if (((previousValue != value) 
							|| (this._Falla.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Falla.Entity = null;
						previousValue.Bitacora.Remove(this);
					}
					this._Falla.Entity = value;
					if ((value != null))
					{
						value.Bitacora.Add(this);
						this._id_falla = value.id_falla;
					}
					else
					{
						this._id_falla = default(string);
					}
					this.SendPropertyChanged("Falla");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Falla")]
	public partial class Falla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_falla;
		
		private string _id_tipo_servicio;
		
		private string _id_tipo_falla;
		
		private string _id_estado_falla;
		
		private string _id_visita_tecnica;
		
		private EntitySet<Bitacora> _Bitacora;
		
		private EntitySet<repuesto_falla> _repuesto_falla;
		
		private EntityRef<Visita_tecnica> _Visita_tecnica;
		
		private EntityRef<Tipo_falla> _Tipo_falla;
		
		private EntityRef<Estado_falla> _Estado_falla;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_fallaChanging(string value);
    partial void Onid_fallaChanged();
    partial void Onid_tipo_servicioChanging(string value);
    partial void Onid_tipo_servicioChanged();
    partial void Onid_tipo_fallaChanging(string value);
    partial void Onid_tipo_fallaChanged();
    partial void Onid_estado_fallaChanging(string value);
    partial void Onid_estado_fallaChanged();
    partial void Onid_visita_tecnicaChanging(string value);
    partial void Onid_visita_tecnicaChanged();
    #endregion
		
		public Falla()
		{
			this._Bitacora = new EntitySet<Bitacora>(new Action<Bitacora>(this.attach_Bitacora), new Action<Bitacora>(this.detach_Bitacora));
			this._repuesto_falla = new EntitySet<repuesto_falla>(new Action<repuesto_falla>(this.attach_repuesto_falla), new Action<repuesto_falla>(this.detach_repuesto_falla));
			this._Visita_tecnica = default(EntityRef<Visita_tecnica>);
			this._Tipo_falla = default(EntityRef<Tipo_falla>);
			this._Estado_falla = default(EntityRef<Estado_falla>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_falla
		{
			get
			{
				return this._id_falla;
			}
			set
			{
				if ((this._id_falla != value))
				{
					this.Onid_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_falla = value;
					this.SendPropertyChanged("id_falla");
					this.Onid_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_tipo_servicio
		{
			get
			{
				return this._id_tipo_servicio;
			}
			set
			{
				if ((this._id_tipo_servicio != value))
				{
					this.Onid_tipo_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_servicio = value;
					this.SendPropertyChanged("id_tipo_servicio");
					this.Onid_tipo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_tipo_falla
		{
			get
			{
				return this._id_tipo_falla;
			}
			set
			{
				if ((this._id_tipo_falla != value))
				{
					if (this._Tipo_falla.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_falla = value;
					this.SendPropertyChanged("id_tipo_falla");
					this.Onid_tipo_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_estado_falla
		{
			get
			{
				return this._id_estado_falla;
			}
			set
			{
				if ((this._id_estado_falla != value))
				{
					if (this._Estado_falla.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estado_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_estado_falla = value;
					this.SendPropertyChanged("id_estado_falla");
					this.Onid_estado_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_visita_tecnica", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_visita_tecnica
		{
			get
			{
				return this._id_visita_tecnica;
			}
			set
			{
				if ((this._id_visita_tecnica != value))
				{
					if (this._Visita_tecnica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_visita_tecnicaChanging(value);
					this.SendPropertyChanging();
					this._id_visita_tecnica = value;
					this.SendPropertyChanged("id_visita_tecnica");
					this.Onid_visita_tecnicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Falla_Bitacora", Storage="_Bitacora", ThisKey="id_falla", OtherKey="id_falla")]
		public EntitySet<Bitacora> Bitacora
		{
			get
			{
				return this._Bitacora;
			}
			set
			{
				this._Bitacora.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Falla_repuesto_falla", Storage="_repuesto_falla", ThisKey="id_falla", OtherKey="id_falla")]
		public EntitySet<repuesto_falla> repuesto_falla
		{
			get
			{
				return this._repuesto_falla;
			}
			set
			{
				this._repuesto_falla.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visita_tecnica_Falla", Storage="_Visita_tecnica", ThisKey="id_visita_tecnica", OtherKey="id_visita_tecnica", IsForeignKey=true)]
		public Visita_tecnica Visita_tecnica
		{
			get
			{
				return this._Visita_tecnica.Entity;
			}
			set
			{
				Visita_tecnica previousValue = this._Visita_tecnica.Entity;
				if (((previousValue != value) 
							|| (this._Visita_tecnica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Visita_tecnica.Entity = null;
						previousValue.Falla.Remove(this);
					}
					this._Visita_tecnica.Entity = value;
					if ((value != null))
					{
						value.Falla.Add(this);
						this._id_visita_tecnica = value.id_visita_tecnica;
					}
					else
					{
						this._id_visita_tecnica = default(string);
					}
					this.SendPropertyChanged("Visita_tecnica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_falla_Falla", Storage="_Tipo_falla", ThisKey="id_tipo_falla", OtherKey="id_tipo_falla", IsForeignKey=true)]
		public Tipo_falla Tipo_falla
		{
			get
			{
				return this._Tipo_falla.Entity;
			}
			set
			{
				Tipo_falla previousValue = this._Tipo_falla.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_falla.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_falla.Entity = null;
						previousValue.Falla.Remove(this);
					}
					this._Tipo_falla.Entity = value;
					if ((value != null))
					{
						value.Falla.Add(this);
						this._id_tipo_falla = value.id_tipo_falla;
					}
					else
					{
						this._id_tipo_falla = default(string);
					}
					this.SendPropertyChanged("Tipo_falla");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_falla_Falla", Storage="_Estado_falla", ThisKey="id_estado_falla", OtherKey="id_estado_falla", IsForeignKey=true)]
		public Estado_falla Estado_falla
		{
			get
			{
				return this._Estado_falla.Entity;
			}
			set
			{
				Estado_falla previousValue = this._Estado_falla.Entity;
				if (((previousValue != value) 
							|| (this._Estado_falla.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado_falla.Entity = null;
						previousValue.Falla.Remove(this);
					}
					this._Estado_falla.Entity = value;
					if ((value != null))
					{
						value.Falla.Add(this);
						this._id_estado_falla = value.id_estado_falla;
					}
					else
					{
						this._id_estado_falla = default(string);
					}
					this.SendPropertyChanged("Estado_falla");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Falla = this;
		}
		
		private void detach_Bitacora(Bitacora entity)
		{
			this.SendPropertyChanging();
			entity.Falla = null;
		}
		
		private void attach_repuesto_falla(repuesto_falla entity)
		{
			this.SendPropertyChanging();
			entity.Falla = this;
		}
		
		private void detach_repuesto_falla(repuesto_falla entity)
		{
			this.SendPropertyChanging();
			entity.Falla = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.repuesto_falla")]
	public partial class repuesto_falla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_repuesto_falla;
		
		private string _id_respuesto;
		
		private string _id_falla;
		
		private decimal _costo_repuesto_falla;
		
		private decimal _precio_repuesto_falla;
		
		private EntityRef<Falla> _Falla;
		
		private EntityRef<Repuesto> _Repuesto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_repuesto_fallaChanging(string value);
    partial void Onid_repuesto_fallaChanged();
    partial void Onid_respuestoChanging(string value);
    partial void Onid_respuestoChanged();
    partial void Onid_fallaChanging(string value);
    partial void Onid_fallaChanged();
    partial void Oncosto_repuesto_fallaChanging(decimal value);
    partial void Oncosto_repuesto_fallaChanged();
    partial void Onprecio_repuesto_fallaChanging(decimal value);
    partial void Onprecio_repuesto_fallaChanged();
    #endregion
		
		public repuesto_falla()
		{
			this._Falla = default(EntityRef<Falla>);
			this._Repuesto = default(EntityRef<Repuesto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_repuesto_falla", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_repuesto_falla
		{
			get
			{
				return this._id_repuesto_falla;
			}
			set
			{
				if ((this._id_repuesto_falla != value))
				{
					this.Onid_repuesto_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_repuesto_falla = value;
					this.SendPropertyChanged("id_repuesto_falla");
					this.Onid_repuesto_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_respuesto", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_respuesto
		{
			get
			{
				return this._id_respuesto;
			}
			set
			{
				if ((this._id_respuesto != value))
				{
					if (this._Repuesto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_respuestoChanging(value);
					this.SendPropertyChanging();
					this._id_respuesto = value;
					this.SendPropertyChanged("id_respuesto");
					this.Onid_respuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_falla
		{
			get
			{
				return this._id_falla;
			}
			set
			{
				if ((this._id_falla != value))
				{
					if (this._Falla.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_falla = value;
					this.SendPropertyChanged("id_falla");
					this.Onid_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_repuesto_falla", DbType="Decimal(8,2) NOT NULL")]
		public decimal costo_repuesto_falla
		{
			get
			{
				return this._costo_repuesto_falla;
			}
			set
			{
				if ((this._costo_repuesto_falla != value))
				{
					this.Oncosto_repuesto_fallaChanging(value);
					this.SendPropertyChanging();
					this._costo_repuesto_falla = value;
					this.SendPropertyChanged("costo_repuesto_falla");
					this.Oncosto_repuesto_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_repuesto_falla", DbType="Decimal(8,2) NOT NULL")]
		public decimal precio_repuesto_falla
		{
			get
			{
				return this._precio_repuesto_falla;
			}
			set
			{
				if ((this._precio_repuesto_falla != value))
				{
					this.Onprecio_repuesto_fallaChanging(value);
					this.SendPropertyChanging();
					this._precio_repuesto_falla = value;
					this.SendPropertyChanged("precio_repuesto_falla");
					this.Onprecio_repuesto_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Falla_repuesto_falla", Storage="_Falla", ThisKey="id_falla", OtherKey="id_falla", IsForeignKey=true)]
		public Falla Falla
		{
			get
			{
				return this._Falla.Entity;
			}
			set
			{
				Falla previousValue = this._Falla.Entity;
				if (((previousValue != value) 
							|| (this._Falla.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Falla.Entity = null;
						previousValue.repuesto_falla.Remove(this);
					}
					this._Falla.Entity = value;
					if ((value != null))
					{
						value.repuesto_falla.Add(this);
						this._id_falla = value.id_falla;
					}
					else
					{
						this._id_falla = default(string);
					}
					this.SendPropertyChanged("Falla");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Repuesto_repuesto_falla", Storage="_Repuesto", ThisKey="id_respuesto", OtherKey="id_respuesto", IsForeignKey=true)]
		public Repuesto Repuesto
		{
			get
			{
				return this._Repuesto.Entity;
			}
			set
			{
				Repuesto previousValue = this._Repuesto.Entity;
				if (((previousValue != value) 
							|| (this._Repuesto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Repuesto.Entity = null;
						previousValue.repuesto_falla.Remove(this);
					}
					this._Repuesto.Entity = value;
					if ((value != null))
					{
						value.repuesto_falla.Add(this);
						this._id_respuesto = value.id_respuesto;
					}
					else
					{
						this._id_respuesto = default(string);
					}
					this.SendPropertyChanged("Repuesto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Repuesto")]
	public partial class Repuesto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_respuesto;
		
		private string _nombre_repuesto;
		
		private decimal _costo_repuesto;
		
		private decimal _precio_repuesto;
		
		private EntitySet<repuesto_falla> _repuesto_falla;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_respuestoChanging(string value);
    partial void Onid_respuestoChanged();
    partial void Onnombre_repuestoChanging(string value);
    partial void Onnombre_repuestoChanged();
    partial void Oncosto_repuestoChanging(decimal value);
    partial void Oncosto_repuestoChanged();
    partial void Onprecio_repuestoChanging(decimal value);
    partial void Onprecio_repuestoChanged();
    #endregion
		
		public Repuesto()
		{
			this._repuesto_falla = new EntitySet<repuesto_falla>(new Action<repuesto_falla>(this.attach_repuesto_falla), new Action<repuesto_falla>(this.detach_repuesto_falla));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_respuesto", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_respuesto
		{
			get
			{
				return this._id_respuesto;
			}
			set
			{
				if ((this._id_respuesto != value))
				{
					this.Onid_respuestoChanging(value);
					this.SendPropertyChanging();
					this._id_respuesto = value;
					this.SendPropertyChanged("id_respuesto");
					this.Onid_respuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_repuesto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_repuesto
		{
			get
			{
				return this._nombre_repuesto;
			}
			set
			{
				if ((this._nombre_repuesto != value))
				{
					this.Onnombre_repuestoChanging(value);
					this.SendPropertyChanging();
					this._nombre_repuesto = value;
					this.SendPropertyChanged("nombre_repuesto");
					this.Onnombre_repuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_repuesto", DbType="Decimal(8,2) NOT NULL")]
		public decimal costo_repuesto
		{
			get
			{
				return this._costo_repuesto;
			}
			set
			{
				if ((this._costo_repuesto != value))
				{
					this.Oncosto_repuestoChanging(value);
					this.SendPropertyChanging();
					this._costo_repuesto = value;
					this.SendPropertyChanged("costo_repuesto");
					this.Oncosto_repuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_repuesto", DbType="Decimal(8,2) NOT NULL")]
		public decimal precio_repuesto
		{
			get
			{
				return this._precio_repuesto;
			}
			set
			{
				if ((this._precio_repuesto != value))
				{
					this.Onprecio_repuestoChanging(value);
					this.SendPropertyChanging();
					this._precio_repuesto = value;
					this.SendPropertyChanged("precio_repuesto");
					this.Onprecio_repuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Repuesto_repuesto_falla", Storage="_repuesto_falla", ThisKey="id_respuesto", OtherKey="id_respuesto")]
		public EntitySet<repuesto_falla> repuesto_falla
		{
			get
			{
				return this._repuesto_falla;
			}
			set
			{
				this._repuesto_falla.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_repuesto_falla(repuesto_falla entity)
		{
			this.SendPropertyChanging();
			entity.Repuesto = this;
		}
		
		private void detach_repuesto_falla(repuesto_falla entity)
		{
			this.SendPropertyChanging();
			entity.Repuesto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_falla")]
	public partial class Tipo_falla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_tipo_falla;
		
		private string _nombre_falla;
		
		private string _descripcion;
		
		private EntitySet<Falla> _Falla;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_fallaChanging(string value);
    partial void Onid_tipo_fallaChanged();
    partial void Onnombre_fallaChanging(string value);
    partial void Onnombre_fallaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Tipo_falla()
		{
			this._Falla = new EntitySet<Falla>(new Action<Falla>(this.attach_Falla), new Action<Falla>(this.detach_Falla));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_tipo_falla
		{
			get
			{
				return this._id_tipo_falla;
			}
			set
			{
				if ((this._id_tipo_falla != value))
				{
					this.Onid_tipo_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_falla = value;
					this.SendPropertyChanged("id_tipo_falla");
					this.Onid_tipo_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_falla", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_falla
		{
			get
			{
				return this._nombre_falla;
			}
			set
			{
				if ((this._nombre_falla != value))
				{
					this.Onnombre_fallaChanging(value);
					this.SendPropertyChanging();
					this._nombre_falla = value;
					this.SendPropertyChanged("nombre_falla");
					this.Onnombre_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_falla_Falla", Storage="_Falla", ThisKey="id_tipo_falla", OtherKey="id_tipo_falla")]
		public EntitySet<Falla> Falla
		{
			get
			{
				return this._Falla;
			}
			set
			{
				this._Falla.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_falla = this;
		}
		
		private void detach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_falla = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_falla")]
	public partial class Estado_falla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_estado_falla;
		
		private EntitySet<Falla> _Falla;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estado_fallaChanging(string value);
    partial void Onid_estado_fallaChanged();
    #endregion
		
		public Estado_falla()
		{
			this._Falla = new EntitySet<Falla>(new Action<Falla>(this.attach_Falla), new Action<Falla>(this.detach_Falla));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_falla", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_estado_falla
		{
			get
			{
				return this._id_estado_falla;
			}
			set
			{
				if ((this._id_estado_falla != value))
				{
					this.Onid_estado_fallaChanging(value);
					this.SendPropertyChanging();
					this._id_estado_falla = value;
					this.SendPropertyChanged("id_estado_falla");
					this.Onid_estado_fallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_falla_Falla", Storage="_Falla", ThisKey="id_estado_falla", OtherKey="id_estado_falla")]
		public EntitySet<Falla> Falla
		{
			get
			{
				return this._Falla;
			}
			set
			{
				this._Falla.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Estado_falla = this;
		}
		
		private void detach_Falla(Falla entity)
		{
			this.SendPropertyChanging();
			entity.Estado_falla = null;
		}
	}
}
#pragma warning restore 1591
