<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql5113.site4now.net;Persist Security Info=True;User ID=db_ac0671_final_admin;Encrypt=False" SettingsObjectName="ExamenFinalBD.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
﻿<?xml version="1.0" encoding="utf-8"?><Database Name="db_ac0671_final" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="id_cliente" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dpi" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_primario" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_secundario" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Contrato" Member="Contrato" ThisKey="id_cliente" OtherKey="id_cliente" Type="Contrato" />
    </Type>
  </Table>
  <Table Name="dbo.Contrato" Member="Contrato">
    <Type Name="Contrato">
      <Column Name="id_contrato" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_info_cobro" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_municipio" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inicio" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_fin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="direccion_instalacion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="saldo_total" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_estado_contrato" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Contrato_Visita_tecnica" Member="Visita_tecnica" ThisKey="id_contrato" OtherKey="id_contrato" Type="Visita_tecnica" />
      <Association Name="Contrato_Servicio" Member="Servicio" ThisKey="id_contrato" OtherKey="id_contrato" Type="Servicio" />
      <Association Name="Cliente_Contrato" Member="Cliente" ThisKey="id_cliente" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Estado_contrato_Contrato" Member="Estado_contrato" ThisKey="id_estado_contrato" OtherKey="id_estado_contrato" Type="Estado_contrato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Estado_contrato" Member="Estado_contrato">
    <Type Name="Estado_contrato">
      <Column Name="id_estado_contrato" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_estado_contrato" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Estado_contrato_Contrato" Member="Contrato" ThisKey="id_estado_contrato" OtherKey="id_estado_contrato" Type="Contrato" />
    </Type>
  </Table>
  <Table Name="dbo.Visita_tecnica" Member="Visita_tecnica">
    <Type Name="Visita_tecnica">
      <Column Name="id_visita_tecnica" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_contrato" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_peloton" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_solicitud" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_ejecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Visita_tecnica_Bitacora" Member="Bitacora" ThisKey="id_visita_tecnica" OtherKey="id_visita_tecnica" Type="Bitacora" />
      <Association Name="Visita_tecnica_Falla" Member="Falla" ThisKey="id_visita_tecnica" OtherKey="id_visita_tecnica" Type="Falla" />
      <Association Name="Contrato_Visita_tecnica" Member="Contrato" ThisKey="id_contrato" OtherKey="id_contrato" Type="Contrato" IsForeignKey="true" />
      <Association Name="Peloton_Visita_tecnica" Member="Peloton" ThisKey="id_peloton" OtherKey="id_peloton" Type="Peloton" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Peloton" Member="Peloton">
    <Type Name="Peloton">
      <Column Name="id_peloton" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_tecnico" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Peloton_Visita_tecnica" Member="Visita_tecnica" ThisKey="id_peloton" OtherKey="id_peloton" Type="Visita_tecnica" />
      <Association Name="Peloton_Bitacora" Member="Bitacora" ThisKey="id_peloton" OtherKey="id_peloton" Type="Bitacora" />
      <Association Name="Tecnico_Peloton" Member="Tecnico" ThisKey="id_tecnico" OtherKey="id_tecnico" Type="Tecnico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tecnico" Member="Tecnico">
    <Type Name="Tecnico">
      <Column Name="id_tecnico" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_tecnico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="direccion_tecnico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nit_tecnico" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="dpi_tecnico" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_nacimiento_tecnico" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_contrato_tecnico" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_despido_tecnico" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Tecnico_Peloton" Member="Peloton" ThisKey="id_tecnico" OtherKey="id_tecnico" Type="Peloton" />
    </Type>
  </Table>
  <Table Name="dbo.Bitacora" Member="Bitacora">
    <Type Name="Bitacora">
      <Column Name="id_bitacora" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_peloton" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="id_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_visita_tecnica" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Peloton_Bitacora" Member="Peloton" ThisKey="id_peloton" OtherKey="id_peloton" Type="Peloton" IsForeignKey="true" />
      <Association Name="Visita_tecnica_Bitacora" Member="Visita_tecnica" ThisKey="id_visita_tecnica" OtherKey="id_visita_tecnica" Type="Visita_tecnica" IsForeignKey="true" />
      <Association Name="Falla_Bitacora" Member="Falla" ThisKey="id_falla" OtherKey="id_falla" Type="Falla" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Falla" Member="Falla">
    <Type Name="Falla">
      <Column Name="id_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_tipo_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_tipo_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_estado_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_visita_tecnica" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Falla_Bitacora" Member="Bitacora" ThisKey="id_falla" OtherKey="id_falla" Type="Bitacora" />
      <Association Name="Falla_repuesto_falla" Member="repuesto_falla" ThisKey="id_falla" OtherKey="id_falla" Type="repuesto_falla" />
      <Association Name="Visita_tecnica_Falla" Member="Visita_tecnica" ThisKey="id_visita_tecnica" OtherKey="id_visita_tecnica" Type="Visita_tecnica" IsForeignKey="true" />
      <Association Name="Tipo_falla_Falla" Member="Tipo_falla" ThisKey="id_tipo_falla" OtherKey="id_tipo_falla" Type="Tipo_falla" IsForeignKey="true" />
      <Association Name="Estado_falla_Falla" Member="Estado_falla" ThisKey="id_estado_falla" OtherKey="id_estado_falla" Type="Estado_falla" IsForeignKey="true" />
      <Association Name="Tipo_servicio_Falla" Member="Tipo_servicio" ThisKey="id_tipo_servicio" OtherKey="id_tipo_servicio" Type="Tipo_servicio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.repuesto_falla" Member="repuesto_falla">
    <Type Name="repuesto_falla">
      <Column Name="id_repuesto_falla" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_respuesto" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="costo_repuesto_falla" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="precio_repuesto_falla" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Association Name="Falla_repuesto_falla" Member="Falla" ThisKey="id_falla" OtherKey="id_falla" Type="Falla" IsForeignKey="true" />
      <Association Name="Repuesto_repuesto_falla" Member="Repuesto" ThisKey="id_respuesto" OtherKey="id_respuesto" Type="Repuesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Repuesto" Member="Repuesto">
    <Type Name="Repuesto">
      <Column Name="id_respuesto" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_repuesto" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="costo_repuesto" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="precio_repuesto" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Association Name="Repuesto_repuesto_falla" Member="repuesto_falla" ThisKey="id_respuesto" OtherKey="id_respuesto" Type="repuesto_falla" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_falla" Member="Tipo_falla">
    <Type Name="Tipo_falla">
      <Column Name="id_tipo_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_falla" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Tipo_falla_Falla" Member="Falla" ThisKey="id_tipo_falla" OtherKey="id_tipo_falla" Type="Falla" />
    </Type>
  </Table>
  <Table Name="dbo.Estado_falla" Member="Estado_falla">
    <Type Name="Estado_falla">
      <Column Name="id_estado_falla" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Estado_falla_Falla" Member="Falla" ThisKey="id_estado_falla" OtherKey="id_estado_falla" Type="Falla" />
    </Type>
  </Table>
  <Table Name="dbo.Servicio" Member="Servicio">
    <Type Name="Servicio">
      <Column Name="id_contrato" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="saldo_pendiente" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_tipo_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_instalacion_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Contrato_Servicio" Member="Contrato" ThisKey="id_contrato" OtherKey="id_contrato" Type="Contrato" IsForeignKey="true" />
      <Association Name="Tipo_servicio_Servicio" Member="Tipo_servicio" ThisKey="id_tipo_servicio" OtherKey="id_tipo_servicio" Type="Tipo_servicio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_servicio" Member="Tipo_servicio">
    <Type Name="Tipo_servicio">
      <Column Name="id_tipo_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_tipo_servicio" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_categoria_servicio" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Tipo_servicio_Falla" Member="Falla" ThisKey="id_tipo_servicio" OtherKey="id_tipo_servicio" Type="Falla" />
      <Association Name="Tipo_servicio_Servicio" Member="Servicio" ThisKey="id_tipo_servicio" OtherKey="id_tipo_servicio" Type="Servicio" />
    </Type>
  </Table>
</Database>