#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalBD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExamenFinalTemporal")]
	public partial class ServiciosDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertTipo_usuario(Tipo_usuario instance);
    partial void UpdateTipo_usuario(Tipo_usuario instance);
    partial void DeleteTipo_usuario(Tipo_usuario instance);
    partial void InsertEstado_usuario(Estado_usuario instance);
    partial void UpdateEstado_usuario(Estado_usuario instance);
    partial void DeleteEstado_usuario(Estado_usuario instance);
    partial void InsertConfiguracion(Configuracion instance);
    partial void UpdateConfiguracion(Configuracion instance);
    partial void DeleteConfiguracion(Configuracion instance);
    partial void InsertMunicipio(Municipio instance);
    partial void UpdateMunicipio(Municipio instance);
    partial void DeleteMunicipio(Municipio instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertInfo_cobro(Info_cobro instance);
    partial void UpdateInfo_cobro(Info_cobro instance);
    partial void DeleteInfo_cobro(Info_cobro instance);
    partial void InsertTipo_servicio(Tipo_servicio instance);
    partial void UpdateTipo_servicio(Tipo_servicio instance);
    partial void DeleteTipo_servicio(Tipo_servicio instance);
    partial void InsertCategoria_servicio(Categoria_servicio instance);
    partial void UpdateCategoria_servicio(Categoria_servicio instance);
    partial void DeleteCategoria_servicio(Categoria_servicio instance);
    partial void InsertVelocidad_internet(Velocidad_internet instance);
    partial void UpdateVelocidad_internet(Velocidad_internet instance);
    partial void DeleteVelocidad_internet(Velocidad_internet instance);
    partial void InsertDisponibilidad_telefono(Disponibilidad_telefono instance);
    partial void UpdateDisponibilidad_telefono(Disponibilidad_telefono instance);
    partial void DeleteDisponibilidad_telefono(Disponibilidad_telefono instance);
    partial void InsertContrato(Contrato instance);
    partial void UpdateContrato(Contrato instance);
    partial void DeleteContrato(Contrato instance);
    partial void InsertServicio(Servicio instance);
    partial void UpdateServicio(Servicio instance);
    partial void DeleteServicio(Servicio instance);
    #endregion
		
		public ServiciosDataContextDataContext() : 
				base(global::ExamenFinalBD.Properties.Settings.Default.ExamenFinalTemporalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ServiciosDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiciosDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiciosDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiciosDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_usuario> Tipo_usuarios
		{
			get
			{
				return this.GetTable<Tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<Estado_usuario> Estado_usuarios
		{
			get
			{
				return this.GetTable<Estado_usuario>();
			}
		}
		
		public System.Data.Linq.Table<Configuracion> Configuracions
		{
			get
			{
				return this.GetTable<Configuracion>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipios
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamentos
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Info_cobro> Info_cobros
		{
			get
			{
				return this.GetTable<Info_cobro>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_servicio> Tipo_servicios
		{
			get
			{
				return this.GetTable<Tipo_servicio>();
			}
		}
		
		public System.Data.Linq.Table<Categoria_servicio> Categoria_servicios
		{
			get
			{
				return this.GetTable<Categoria_servicio>();
			}
		}
		
		public System.Data.Linq.Table<Velocidad_internet> Velocidad_internets
		{
			get
			{
				return this.GetTable<Velocidad_internet>();
			}
		}
		
		public System.Data.Linq.Table<Disponibilidad_telefono> Disponibilidad_telefonos
		{
			get
			{
				return this.GetTable<Disponibilidad_telefono>();
			}
		}
		
		public System.Data.Linq.Table<Contrato> Contratos
		{
			get
			{
				return this.GetTable<Contrato>();
			}
		}
		
		public System.Data.Linq.Table<Servicio> Servicios
		{
			get
			{
				return this.GetTable<Servicio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_usuario;
		
		private string _nombre_usuario;
		
		private string _password;
		
		private string _id_tipo_usuario;
		
		private string _id_estado_usuario;
		
		private EntityRef<Tipo_usuario> _Tipo_usuario;
		
		private EntityRef<Estado_usuario> _Estado_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(string value);
    partial void Onid_usuarioChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onid_tipo_usuarioChanging(string value);
    partial void Onid_tipo_usuarioChanged();
    partial void Onid_estado_usuarioChanging(string value);
    partial void Onid_estado_usuarioChanged();
    #endregion
		
		public Usuario()
		{
			this._Tipo_usuario = default(EntityRef<Tipo_usuario>);
			this._Estado_usuario = default(EntityRef<Estado_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_tipo_usuario
		{
			get
			{
				return this._id_tipo_usuario;
			}
			set
			{
				if ((this._id_tipo_usuario != value))
				{
					if (this._Tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_usuario = value;
					this.SendPropertyChanged("id_tipo_usuario");
					this.Onid_tipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_estado_usuario
		{
			get
			{
				return this._id_estado_usuario;
			}
			set
			{
				if ((this._id_estado_usuario != value))
				{
					if (this._Estado_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_estado_usuario = value;
					this.SendPropertyChanged("id_estado_usuario");
					this.Onid_estado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_usuario_Usuario", Storage="_Tipo_usuario", ThisKey="id_tipo_usuario", OtherKey="id_tipo_usuario", IsForeignKey=true)]
		public Tipo_usuario Tipo_usuario
		{
			get
			{
				return this._Tipo_usuario.Entity;
			}
			set
			{
				Tipo_usuario previousValue = this._Tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_usuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_tipo_usuario = value.id_tipo_usuario;
					}
					else
					{
						this._id_tipo_usuario = default(string);
					}
					this.SendPropertyChanged("Tipo_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_usuario_Usuario", Storage="_Estado_usuario", ThisKey="id_estado_usuario", OtherKey="id_estado_usuario", IsForeignKey=true)]
		public Estado_usuario Estado_usuario
		{
			get
			{
				return this._Estado_usuario.Entity;
			}
			set
			{
				Estado_usuario previousValue = this._Estado_usuario.Entity;
				if (((previousValue != value) 
							|| (this._Estado_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado_usuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Estado_usuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_estado_usuario = value.id_estado_usuario;
					}
					else
					{
						this._id_estado_usuario = default(string);
					}
					this.SendPropertyChanged("Estado_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_usuario")]
	public partial class Tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_tipo_usuario;
		
		private string _nombre_tipo_usuario;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_usuarioChanging(string value);
    partial void Onid_tipo_usuarioChanged();
    partial void Onnombre_tipo_usuarioChanging(string value);
    partial void Onnombre_tipo_usuarioChanged();
    #endregion
		
		public Tipo_usuario()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_tipo_usuario
		{
			get
			{
				return this._id_tipo_usuario;
			}
			set
			{
				if ((this._id_tipo_usuario != value))
				{
					this.Onid_tipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_usuario = value;
					this.SendPropertyChanged("id_tipo_usuario");
					this.Onid_tipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tipo_usuario", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string nombre_tipo_usuario
		{
			get
			{
				return this._nombre_tipo_usuario;
			}
			set
			{
				if ((this._nombre_tipo_usuario != value))
				{
					this.Onnombre_tipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_tipo_usuario = value;
					this.SendPropertyChanged("nombre_tipo_usuario");
					this.Onnombre_tipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_usuario_Usuario", Storage="_Usuarios", ThisKey="id_tipo_usuario", OtherKey="id_tipo_usuario")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_usuario = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_usuario")]
	public partial class Estado_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_estado_usuario;
		
		private string _nombre_estado_usuario;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estado_usuarioChanging(string value);
    partial void Onid_estado_usuarioChanged();
    partial void Onnombre_estado_usuarioChanging(string value);
    partial void Onnombre_estado_usuarioChanged();
    #endregion
		
		public Estado_usuario()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_usuario", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_estado_usuario
		{
			get
			{
				return this._id_estado_usuario;
			}
			set
			{
				if ((this._id_estado_usuario != value))
				{
					this.Onid_estado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_estado_usuario = value;
					this.SendPropertyChanged("id_estado_usuario");
					this.Onid_estado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_estado_usuario", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string nombre_estado_usuario
		{
			get
			{
				return this._nombre_estado_usuario;
			}
			set
			{
				if ((this._nombre_estado_usuario != value))
				{
					this.Onnombre_estado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_estado_usuario = value;
					this.SendPropertyChanged("nombre_estado_usuario");
					this.Onnombre_estado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_usuario_Usuario", Storage="_Usuarios", ThisKey="id_estado_usuario", OtherKey="id_estado_usuario")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Estado_usuario = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Estado_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Configuracion")]
	public partial class Configuracion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_configuracion;
		
		private decimal _monto_mora;
		
		private string _monto_inscripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_configuracionChanging(string value);
    partial void Onid_configuracionChanged();
    partial void Onmonto_moraChanging(decimal value);
    partial void Onmonto_moraChanged();
    partial void Onmonto_inscripcionChanging(string value);
    partial void Onmonto_inscripcionChanged();
    #endregion
		
		public Configuracion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_configuracion", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_configuracion
		{
			get
			{
				return this._id_configuracion;
			}
			set
			{
				if ((this._id_configuracion != value))
				{
					this.Onid_configuracionChanging(value);
					this.SendPropertyChanging();
					this._id_configuracion = value;
					this.SendPropertyChanged("id_configuracion");
					this.Onid_configuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_mora", DbType="Decimal(8,2) NOT NULL")]
		public decimal monto_mora
		{
			get
			{
				return this._monto_mora;
			}
			set
			{
				if ((this._monto_mora != value))
				{
					this.Onmonto_moraChanging(value);
					this.SendPropertyChanging();
					this._monto_mora = value;
					this.SendPropertyChanged("monto_mora");
					this.Onmonto_moraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_inscripcion", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string monto_inscripcion
		{
			get
			{
				return this._monto_inscripcion;
			}
			set
			{
				if ((this._monto_inscripcion != value))
				{
					this.Onmonto_inscripcionChanging(value);
					this.SendPropertyChanging();
					this._monto_inscripcion = value;
					this.SendPropertyChanged("monto_inscripcion");
					this.Onmonto_inscripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipio")]
	public partial class Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_municipio;
		
		private string _nombre_municipio;
		
		private string _id_departamento;
		
		private EntitySet<Info_cobro> _Info_cobros;
		
		private EntitySet<Contrato> _Contratos;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_municipioChanging(string value);
    partial void Onid_municipioChanged();
    partial void Onnombre_municipioChanging(string value);
    partial void Onnombre_municipioChanged();
    partial void Onid_departamentoChanging(string value);
    partial void Onid_departamentoChanged();
    #endregion
		
		public Municipio()
		{
			this._Info_cobros = new EntitySet<Info_cobro>(new Action<Info_cobro>(this.attach_Info_cobros), new Action<Info_cobro>(this.detach_Info_cobros));
			this._Contratos = new EntitySet<Contrato>(new Action<Contrato>(this.attach_Contratos), new Action<Contrato>(this.detach_Contratos));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_municipio", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string nombre_municipio
		{
			get
			{
				return this._nombre_municipio;
			}
			set
			{
				if ((this._nombre_municipio != value))
				{
					this.Onnombre_municipioChanging(value);
					this.SendPropertyChanging();
					this._nombre_municipio = value;
					this.SendPropertyChanged("nombre_municipio");
					this.Onnombre_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Info_cobro", Storage="_Info_cobros", ThisKey="id_municipio", OtherKey="id_municipio")]
		public EntitySet<Info_cobro> Info_cobros
		{
			get
			{
				return this._Info_cobros;
			}
			set
			{
				this._Info_cobros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Contrato", Storage="_Contratos", ThisKey="id_municipio", OtherKey="id_municipio")]
		public EntitySet<Contrato> Contratos
		{
			get
			{
				return this._Contratos;
			}
			set
			{
				this._Contratos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Municipio", Storage="_Departamento", ThisKey="id_departamento", OtherKey="id_departamento", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Municipios.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Municipios.Add(this);
						this._id_departamento = value.id_departamento;
					}
					else
					{
						this._id_departamento = default(string);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Info_cobros(Info_cobro entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = this;
		}
		
		private void detach_Info_cobros(Info_cobro entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = null;
		}
		
		private void attach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = this;
		}
		
		private void detach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Municipio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_departamento;
		
		private string _nombre_departamento;
		
		private EntitySet<Municipio> _Municipios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_departamentoChanging(string value);
    partial void Onid_departamentoChanged();
    partial void Onnombre_departamentoChanging(string value);
    partial void Onnombre_departamentoChanged();
    #endregion
		
		public Departamento()
		{
			this._Municipios = new EntitySet<Municipio>(new Action<Municipio>(this.attach_Municipios), new Action<Municipio>(this.detach_Municipios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_departamento", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string nombre_departamento
		{
			get
			{
				return this._nombre_departamento;
			}
			set
			{
				if ((this._nombre_departamento != value))
				{
					this.Onnombre_departamentoChanging(value);
					this.SendPropertyChanging();
					this._nombre_departamento = value;
					this.SendPropertyChanged("nombre_departamento");
					this.Onnombre_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Municipio", Storage="_Municipios", ThisKey="id_departamento", OtherKey="id_departamento")]
		public EntitySet<Municipio> Municipios
		{
			get
			{
				return this._Municipios;
			}
			set
			{
				this._Municipios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Municipios(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Municipios(Municipio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_cliente;
		
		private string _dpi;
		
		private string _nombre;
		
		private string _telefono_primario;
		
		private string _telefono_secundario;
		
		private string _email;
		
		private EntitySet<Contrato> _Contratos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    partial void OndpiChanging(string value);
    partial void OndpiChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ontelefono_primarioChanging(string value);
    partial void Ontelefono_primarioChanged();
    partial void Ontelefono_secundarioChanging(string value);
    partial void Ontelefono_secundarioChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Cliente()
		{
			this._Contratos = new EntitySet<Contrato>(new Action<Contrato>(this.attach_Contratos), new Action<Contrato>(this.detach_Contratos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string dpi
		{
			get
			{
				return this._dpi;
			}
			set
			{
				if ((this._dpi != value))
				{
					this.OndpiChanging(value);
					this.SendPropertyChanging();
					this._dpi = value;
					this.SendPropertyChanged("dpi");
					this.OndpiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_primario", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string telefono_primario
		{
			get
			{
				return this._telefono_primario;
			}
			set
			{
				if ((this._telefono_primario != value))
				{
					this.Ontelefono_primarioChanging(value);
					this.SendPropertyChanging();
					this._telefono_primario = value;
					this.SendPropertyChanged("telefono_primario");
					this.Ontelefono_primarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_secundario", DbType="Char(10)")]
		public string telefono_secundario
		{
			get
			{
				return this._telefono_secundario;
			}
			set
			{
				if ((this._telefono_secundario != value))
				{
					this.Ontelefono_secundarioChanging(value);
					this.SendPropertyChanging();
					this._telefono_secundario = value;
					this.SendPropertyChanged("telefono_secundario");
					this.Ontelefono_secundarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contrato", Storage="_Contratos", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<Contrato> Contratos
		{
			get
			{
				return this._Contratos;
			}
			set
			{
				this._Contratos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Info_cobro")]
	public partial class Info_cobro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_info_cobro;
		
		private string _telefono;
		
		private string _direccion;
		
		private string _id_municipio;
		
		private EntitySet<Contrato> _Contratos;
		
		private EntityRef<Municipio> _Municipio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_info_cobroChanging(string value);
    partial void Onid_info_cobroChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Onid_municipioChanging(string value);
    partial void Onid_municipioChanged();
    #endregion
		
		public Info_cobro()
		{
			this._Contratos = new EntitySet<Contrato>(new Action<Contrato>(this.attach_Contratos), new Action<Contrato>(this.detach_Contratos));
			this._Municipio = default(EntityRef<Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_info_cobro", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_info_cobro
		{
			get
			{
				return this._id_info_cobro;
			}
			set
			{
				if ((this._id_info_cobro != value))
				{
					this.Onid_info_cobroChanging(value);
					this.SendPropertyChanging();
					this._id_info_cobro = value;
					this.SendPropertyChanged("id_info_cobro");
					this.Onid_info_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Info_cobro_Contrato", Storage="_Contratos", ThisKey="id_info_cobro", OtherKey="id_info_cobro")]
		public EntitySet<Contrato> Contratos
		{
			get
			{
				return this._Contratos;
			}
			set
			{
				this._Contratos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Info_cobro", Storage="_Municipio", ThisKey="id_municipio", OtherKey="id_municipio", IsForeignKey=true)]
		public Municipio Municipio
		{
			get
			{
				return this._Municipio.Entity;
			}
			set
			{
				Municipio previousValue = this._Municipio.Entity;
				if (((previousValue != value) 
							|| (this._Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Municipio.Entity = null;
						previousValue.Info_cobros.Remove(this);
					}
					this._Municipio.Entity = value;
					if ((value != null))
					{
						value.Info_cobros.Add(this);
						this._id_municipio = value.id_municipio;
					}
					else
					{
						this._id_municipio = default(string);
					}
					this.SendPropertyChanged("Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Info_cobro = this;
		}
		
		private void detach_Contratos(Contrato entity)
		{
			this.SendPropertyChanging();
			entity.Info_cobro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_servicio")]
	public partial class Tipo_servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_tipo_servicio;
		
		private string _nombre_tipo_servicio;
		
		private string _id_categoria_servicio;
		
		private EntitySet<Servicio> _Servicios;
		
		private EntityRef<Categoria_servicio> _Categoria_servicio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_servicioChanging(string value);
    partial void Onid_tipo_servicioChanged();
    partial void Onnombre_tipo_servicioChanging(string value);
    partial void Onnombre_tipo_servicioChanged();
    partial void Onid_categoria_servicioChanging(string value);
    partial void Onid_categoria_servicioChanged();
    #endregion
		
		public Tipo_servicio()
		{
			this._Servicios = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicios), new Action<Servicio>(this.detach_Servicios));
			this._Categoria_servicio = default(EntityRef<Categoria_servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_tipo_servicio
		{
			get
			{
				return this._id_tipo_servicio;
			}
			set
			{
				if ((this._id_tipo_servicio != value))
				{
					this.Onid_tipo_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_servicio = value;
					this.SendPropertyChanged("id_tipo_servicio");
					this.Onid_tipo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tipo_servicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_tipo_servicio
		{
			get
			{
				return this._nombre_tipo_servicio;
			}
			set
			{
				if ((this._nombre_tipo_servicio != value))
				{
					this.Onnombre_tipo_servicioChanging(value);
					this.SendPropertyChanging();
					this._nombre_tipo_servicio = value;
					this.SendPropertyChanged("nombre_tipo_servicio");
					this.Onnombre_tipo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_categoria_servicio
		{
			get
			{
				return this._id_categoria_servicio;
			}
			set
			{
				if ((this._id_categoria_servicio != value))
				{
					if (this._Categoria_servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoria_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_categoria_servicio = value;
					this.SendPropertyChanged("id_categoria_servicio");
					this.Onid_categoria_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_servicio_Servicio", Storage="_Servicios", ThisKey="id_tipo_servicio", OtherKey="id_tipo_servicio")]
		public EntitySet<Servicio> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_servicio_Tipo_servicio", Storage="_Categoria_servicio", ThisKey="id_categoria_servicio", OtherKey="id_categoria_servicio", IsForeignKey=true)]
		public Categoria_servicio Categoria_servicio
		{
			get
			{
				return this._Categoria_servicio.Entity;
			}
			set
			{
				Categoria_servicio previousValue = this._Categoria_servicio.Entity;
				if (((previousValue != value) 
							|| (this._Categoria_servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria_servicio.Entity = null;
						previousValue.Tipo_servicios.Remove(this);
					}
					this._Categoria_servicio.Entity = value;
					if ((value != null))
					{
						value.Tipo_servicios.Add(this);
						this._id_categoria_servicio = value.id_categoria_servicio;
					}
					else
					{
						this._id_categoria_servicio = default(string);
					}
					this.SendPropertyChanged("Categoria_servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_servicio = this;
		}
		
		private void detach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_servicio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria_servicio")]
	public partial class Categoria_servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_categoria_servicio;
		
		private string _id_disponibilidad_telefono;
		
		private string _id_velocidad_internet;
		
		private string _nombre_categoria_servicio;
		
		private EntitySet<Tipo_servicio> _Tipo_servicios;
		
		private EntityRef<Velocidad_internet> _Velocidad_internet;
		
		private EntityRef<Disponibilidad_telefono> _Disponibilidad_telefono;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoria_servicioChanging(string value);
    partial void Onid_categoria_servicioChanged();
    partial void Onid_disponibilidad_telefonoChanging(string value);
    partial void Onid_disponibilidad_telefonoChanged();
    partial void Onid_velocidad_internetChanging(string value);
    partial void Onid_velocidad_internetChanged();
    partial void Onnombre_categoria_servicioChanging(string value);
    partial void Onnombre_categoria_servicioChanged();
    #endregion
		
		public Categoria_servicio()
		{
			this._Tipo_servicios = new EntitySet<Tipo_servicio>(new Action<Tipo_servicio>(this.attach_Tipo_servicios), new Action<Tipo_servicio>(this.detach_Tipo_servicios));
			this._Velocidad_internet = default(EntityRef<Velocidad_internet>);
			this._Disponibilidad_telefono = default(EntityRef<Disponibilidad_telefono>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_categoria_servicio
		{
			get
			{
				return this._id_categoria_servicio;
			}
			set
			{
				if ((this._id_categoria_servicio != value))
				{
					this.Onid_categoria_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_categoria_servicio = value;
					this.SendPropertyChanged("id_categoria_servicio");
					this.Onid_categoria_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_disponibilidad_telefono", DbType="NVarChar(10)")]
		public string id_disponibilidad_telefono
		{
			get
			{
				return this._id_disponibilidad_telefono;
			}
			set
			{
				if ((this._id_disponibilidad_telefono != value))
				{
					if (this._Disponibilidad_telefono.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_disponibilidad_telefonoChanging(value);
					this.SendPropertyChanging();
					this._id_disponibilidad_telefono = value;
					this.SendPropertyChanged("id_disponibilidad_telefono");
					this.Onid_disponibilidad_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_velocidad_internet", DbType="NVarChar(6)")]
		public string id_velocidad_internet
		{
			get
			{
				return this._id_velocidad_internet;
			}
			set
			{
				if ((this._id_velocidad_internet != value))
				{
					if (this._Velocidad_internet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_velocidad_internetChanging(value);
					this.SendPropertyChanging();
					this._id_velocidad_internet = value;
					this.SendPropertyChanged("id_velocidad_internet");
					this.Onid_velocidad_internetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_categoria_servicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_categoria_servicio
		{
			get
			{
				return this._nombre_categoria_servicio;
			}
			set
			{
				if ((this._nombre_categoria_servicio != value))
				{
					this.Onnombre_categoria_servicioChanging(value);
					this.SendPropertyChanging();
					this._nombre_categoria_servicio = value;
					this.SendPropertyChanged("nombre_categoria_servicio");
					this.Onnombre_categoria_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_servicio_Tipo_servicio", Storage="_Tipo_servicios", ThisKey="id_categoria_servicio", OtherKey="id_categoria_servicio")]
		public EntitySet<Tipo_servicio> Tipo_servicios
		{
			get
			{
				return this._Tipo_servicios;
			}
			set
			{
				this._Tipo_servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Velocidad_internet_Categoria_servicio", Storage="_Velocidad_internet", ThisKey="id_velocidad_internet", OtherKey="id_velocidad_internet", IsForeignKey=true)]
		public Velocidad_internet Velocidad_internet
		{
			get
			{
				return this._Velocidad_internet.Entity;
			}
			set
			{
				Velocidad_internet previousValue = this._Velocidad_internet.Entity;
				if (((previousValue != value) 
							|| (this._Velocidad_internet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Velocidad_internet.Entity = null;
						previousValue.Categoria_servicios.Remove(this);
					}
					this._Velocidad_internet.Entity = value;
					if ((value != null))
					{
						value.Categoria_servicios.Add(this);
						this._id_velocidad_internet = value.id_velocidad_internet;
					}
					else
					{
						this._id_velocidad_internet = default(string);
					}
					this.SendPropertyChanged("Velocidad_internet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disponibilidad_telefono_Categoria_servicio", Storage="_Disponibilidad_telefono", ThisKey="id_disponibilidad_telefono", OtherKey="id_disponibilidad_telefono", IsForeignKey=true)]
		public Disponibilidad_telefono Disponibilidad_telefono
		{
			get
			{
				return this._Disponibilidad_telefono.Entity;
			}
			set
			{
				Disponibilidad_telefono previousValue = this._Disponibilidad_telefono.Entity;
				if (((previousValue != value) 
							|| (this._Disponibilidad_telefono.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Disponibilidad_telefono.Entity = null;
						previousValue.Categoria_servicios.Remove(this);
					}
					this._Disponibilidad_telefono.Entity = value;
					if ((value != null))
					{
						value.Categoria_servicios.Add(this);
						this._id_disponibilidad_telefono = value.id_disponibilidad_telefono;
					}
					else
					{
						this._id_disponibilidad_telefono = default(string);
					}
					this.SendPropertyChanged("Disponibilidad_telefono");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tipo_servicios(Tipo_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Categoria_servicio = this;
		}
		
		private void detach_Tipo_servicios(Tipo_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Categoria_servicio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Velocidad_internet")]
	public partial class Velocidad_internet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_velocidad_internet;
		
		private int _velocidad_subida;
		
		private int _velocidad_descarga;
		
		private EntitySet<Categoria_servicio> _Categoria_servicios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_velocidad_internetChanging(string value);
    partial void Onid_velocidad_internetChanged();
    partial void Onvelocidad_subidaChanging(int value);
    partial void Onvelocidad_subidaChanged();
    partial void Onvelocidad_descargaChanging(int value);
    partial void Onvelocidad_descargaChanged();
    #endregion
		
		public Velocidad_internet()
		{
			this._Categoria_servicios = new EntitySet<Categoria_servicio>(new Action<Categoria_servicio>(this.attach_Categoria_servicios), new Action<Categoria_servicio>(this.detach_Categoria_servicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_velocidad_internet", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_velocidad_internet
		{
			get
			{
				return this._id_velocidad_internet;
			}
			set
			{
				if ((this._id_velocidad_internet != value))
				{
					this.Onid_velocidad_internetChanging(value);
					this.SendPropertyChanging();
					this._id_velocidad_internet = value;
					this.SendPropertyChanged("id_velocidad_internet");
					this.Onid_velocidad_internetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_velocidad_subida", DbType="Int NOT NULL")]
		public int velocidad_subida
		{
			get
			{
				return this._velocidad_subida;
			}
			set
			{
				if ((this._velocidad_subida != value))
				{
					this.Onvelocidad_subidaChanging(value);
					this.SendPropertyChanging();
					this._velocidad_subida = value;
					this.SendPropertyChanged("velocidad_subida");
					this.Onvelocidad_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_velocidad_descarga", DbType="Int NOT NULL")]
		public int velocidad_descarga
		{
			get
			{
				return this._velocidad_descarga;
			}
			set
			{
				if ((this._velocidad_descarga != value))
				{
					this.Onvelocidad_descargaChanging(value);
					this.SendPropertyChanging();
					this._velocidad_descarga = value;
					this.SendPropertyChanged("velocidad_descarga");
					this.Onvelocidad_descargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Velocidad_internet_Categoria_servicio", Storage="_Categoria_servicios", ThisKey="id_velocidad_internet", OtherKey="id_velocidad_internet")]
		public EntitySet<Categoria_servicio> Categoria_servicios
		{
			get
			{
				return this._Categoria_servicios;
			}
			set
			{
				this._Categoria_servicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Categoria_servicios(Categoria_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Velocidad_internet = this;
		}
		
		private void detach_Categoria_servicios(Categoria_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Velocidad_internet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Disponibilidad_telefono")]
	public partial class Disponibilidad_telefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_disponibilidad_telefono;
		
		private int _cantidad_minutos;
		
		private EntitySet<Categoria_servicio> _Categoria_servicios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_disponibilidad_telefonoChanging(string value);
    partial void Onid_disponibilidad_telefonoChanged();
    partial void Oncantidad_minutosChanging(int value);
    partial void Oncantidad_minutosChanged();
    #endregion
		
		public Disponibilidad_telefono()
		{
			this._Categoria_servicios = new EntitySet<Categoria_servicio>(new Action<Categoria_servicio>(this.attach_Categoria_servicios), new Action<Categoria_servicio>(this.detach_Categoria_servicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_disponibilidad_telefono", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_disponibilidad_telefono
		{
			get
			{
				return this._id_disponibilidad_telefono;
			}
			set
			{
				if ((this._id_disponibilidad_telefono != value))
				{
					this.Onid_disponibilidad_telefonoChanging(value);
					this.SendPropertyChanging();
					this._id_disponibilidad_telefono = value;
					this.SendPropertyChanged("id_disponibilidad_telefono");
					this.Onid_disponibilidad_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_minutos", DbType="Int NOT NULL")]
		public int cantidad_minutos
		{
			get
			{
				return this._cantidad_minutos;
			}
			set
			{
				if ((this._cantidad_minutos != value))
				{
					this.Oncantidad_minutosChanging(value);
					this.SendPropertyChanging();
					this._cantidad_minutos = value;
					this.SendPropertyChanged("cantidad_minutos");
					this.Oncantidad_minutosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disponibilidad_telefono_Categoria_servicio", Storage="_Categoria_servicios", ThisKey="id_disponibilidad_telefono", OtherKey="id_disponibilidad_telefono")]
		public EntitySet<Categoria_servicio> Categoria_servicios
		{
			get
			{
				return this._Categoria_servicios;
			}
			set
			{
				this._Categoria_servicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Categoria_servicios(Categoria_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Disponibilidad_telefono = this;
		}
		
		private void detach_Categoria_servicios(Categoria_servicio entity)
		{
			this.SendPropertyChanging();
			entity.Disponibilidad_telefono = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contrato")]
	public partial class Contrato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_contrato;
		
		private string _id_info_cobro;
		
		private string _id_municipio;
		
		private string _id_cliente;
		
		private string _fecha_inicio;
		
		private System.DateTime _fecha_fin;
		
		private string _direccion_instalacion;
		
		private decimal _saldo_total;
		
		private string _id_estado_contrato;
		
		private EntitySet<Servicio> _Servicios;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Info_cobro> _Info_cobro;
		
		private EntityRef<Municipio> _Municipio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contratoChanging(string value);
    partial void Onid_contratoChanged();
    partial void Onid_info_cobroChanging(string value);
    partial void Onid_info_cobroChanged();
    partial void Onid_municipioChanging(string value);
    partial void Onid_municipioChanged();
    partial void Onid_clienteChanging(string value);
    partial void Onid_clienteChanged();
    partial void Onfecha_inicioChanging(string value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void Ondireccion_instalacionChanging(string value);
    partial void Ondireccion_instalacionChanged();
    partial void Onsaldo_totalChanging(decimal value);
    partial void Onsaldo_totalChanged();
    partial void Onid_estado_contratoChanging(string value);
    partial void Onid_estado_contratoChanged();
    #endregion
		
		public Contrato()
		{
			this._Servicios = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicios), new Action<Servicio>(this.detach_Servicios));
			this._Cliente = default(EntityRef<Cliente>);
			this._Info_cobro = default(EntityRef<Info_cobro>);
			this._Municipio = default(EntityRef<Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contrato", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_contrato
		{
			get
			{
				return this._id_contrato;
			}
			set
			{
				if ((this._id_contrato != value))
				{
					this.Onid_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_contrato = value;
					this.SendPropertyChanged("id_contrato");
					this.Onid_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_info_cobro", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_info_cobro
		{
			get
			{
				return this._id_info_cobro;
			}
			set
			{
				if ((this._id_info_cobro != value))
				{
					if (this._Info_cobro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_info_cobroChanging(value);
					this.SendPropertyChanging();
					this._id_info_cobro = value;
					this.SendPropertyChanged("id_info_cobro");
					this.Onid_info_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					if (this._Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_instalacion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_instalacion
		{
			get
			{
				return this._direccion_instalacion;
			}
			set
			{
				if ((this._direccion_instalacion != value))
				{
					this.Ondireccion_instalacionChanging(value);
					this.SendPropertyChanging();
					this._direccion_instalacion = value;
					this.SendPropertyChanged("direccion_instalacion");
					this.Ondireccion_instalacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_total", DbType="Decimal(8,2) NOT NULL")]
		public decimal saldo_total
		{
			get
			{
				return this._saldo_total;
			}
			set
			{
				if ((this._saldo_total != value))
				{
					this.Onsaldo_totalChanging(value);
					this.SendPropertyChanging();
					this._saldo_total = value;
					this.SendPropertyChanged("saldo_total");
					this.Onsaldo_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_contrato", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string id_estado_contrato
		{
			get
			{
				return this._id_estado_contrato;
			}
			set
			{
				if ((this._id_estado_contrato != value))
				{
					this.Onid_estado_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_estado_contrato = value;
					this.SendPropertyChanged("id_estado_contrato");
					this.Onid_estado_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contrato_Servicio", Storage="_Servicios", ThisKey="id_contrato", OtherKey="id_contrato")]
		public EntitySet<Servicio> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Contrato", Storage="_Cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Contratos.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Contratos.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Info_cobro_Contrato", Storage="_Info_cobro", ThisKey="id_info_cobro", OtherKey="id_info_cobro", IsForeignKey=true)]
		public Info_cobro Info_cobro
		{
			get
			{
				return this._Info_cobro.Entity;
			}
			set
			{
				Info_cobro previousValue = this._Info_cobro.Entity;
				if (((previousValue != value) 
							|| (this._Info_cobro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Info_cobro.Entity = null;
						previousValue.Contratos.Remove(this);
					}
					this._Info_cobro.Entity = value;
					if ((value != null))
					{
						value.Contratos.Add(this);
						this._id_info_cobro = value.id_info_cobro;
					}
					else
					{
						this._id_info_cobro = default(string);
					}
					this.SendPropertyChanged("Info_cobro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Municipio_Contrato", Storage="_Municipio", ThisKey="id_municipio", OtherKey="id_municipio", IsForeignKey=true)]
		public Municipio Municipio
		{
			get
			{
				return this._Municipio.Entity;
			}
			set
			{
				Municipio previousValue = this._Municipio.Entity;
				if (((previousValue != value) 
							|| (this._Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Municipio.Entity = null;
						previousValue.Contratos.Remove(this);
					}
					this._Municipio.Entity = value;
					if ((value != null))
					{
						value.Contratos.Add(this);
						this._id_municipio = value.id_municipio;
					}
					else
					{
						this._id_municipio = default(string);
					}
					this.SendPropertyChanged("Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Contrato = this;
		}
		
		private void detach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Contrato = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicio")]
	public partial class Servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_contrato;
		
		private string _id_servicio;
		
		private decimal _saldo_pendiente;
		
		private string _id_tipo_servicio;
		
		private EntityRef<Contrato> _Contrato;
		
		private EntityRef<Tipo_servicio> _Tipo_servicio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contratoChanging(string value);
    partial void Onid_contratoChanged();
    partial void Onid_servicioChanging(string value);
    partial void Onid_servicioChanged();
    partial void Onsaldo_pendienteChanging(decimal value);
    partial void Onsaldo_pendienteChanged();
    partial void Onid_tipo_servicioChanging(string value);
    partial void Onid_tipo_servicioChanged();
    #endregion
		
		public Servicio()
		{
			this._Contrato = default(EntityRef<Contrato>);
			this._Tipo_servicio = default(EntityRef<Tipo_servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contrato", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_contrato
		{
			get
			{
				return this._id_contrato;
			}
			set
			{
				if ((this._id_contrato != value))
				{
					if (this._Contrato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_contratoChanging(value);
					this.SendPropertyChanging();
					this._id_contrato = value;
					this.SendPropertyChanged("id_contrato");
					this.Onid_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_servicio
		{
			get
			{
				return this._id_servicio;
			}
			set
			{
				if ((this._id_servicio != value))
				{
					this.Onid_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_servicio = value;
					this.SendPropertyChanged("id_servicio");
					this.Onid_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_pendiente", DbType="Decimal(8,2) NOT NULL")]
		public decimal saldo_pendiente
		{
			get
			{
				return this._saldo_pendiente;
			}
			set
			{
				if ((this._saldo_pendiente != value))
				{
					this.Onsaldo_pendienteChanging(value);
					this.SendPropertyChanging();
					this._saldo_pendiente = value;
					this.SendPropertyChanged("saldo_pendiente");
					this.Onsaldo_pendienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_servicio", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string id_tipo_servicio
		{
			get
			{
				return this._id_tipo_servicio;
			}
			set
			{
				if ((this._id_tipo_servicio != value))
				{
					if (this._Tipo_servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_servicioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_servicio = value;
					this.SendPropertyChanged("id_tipo_servicio");
					this.Onid_tipo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contrato_Servicio", Storage="_Contrato", ThisKey="id_contrato", OtherKey="id_contrato", IsForeignKey=true)]
		public Contrato Contrato
		{
			get
			{
				return this._Contrato.Entity;
			}
			set
			{
				Contrato previousValue = this._Contrato.Entity;
				if (((previousValue != value) 
							|| (this._Contrato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contrato.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Contrato.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._id_contrato = value.id_contrato;
					}
					else
					{
						this._id_contrato = default(string);
					}
					this.SendPropertyChanged("Contrato");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_servicio_Servicio", Storage="_Tipo_servicio", ThisKey="id_tipo_servicio", OtherKey="id_tipo_servicio", IsForeignKey=true)]
		public Tipo_servicio Tipo_servicio
		{
			get
			{
				return this._Tipo_servicio.Entity;
			}
			set
			{
				Tipo_servicio previousValue = this._Tipo_servicio.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_servicio.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Tipo_servicio.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._id_tipo_servicio = value.id_tipo_servicio;
					}
					else
					{
						this._id_tipo_servicio = default(string);
					}
					this.SendPropertyChanged("Tipo_servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
